// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPedidos.Data;

#nullable disable

namespace SistemaPedidos.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPedidos.Core.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsPedidos");
                });

            modelBuilder.Entity("SistemaPedidos.Core.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaPedidos.Core.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasDiscriminator<string>("TipoProducto").HasValue("Producto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaPedidos.Core.Models.ProductoDigital", b =>
                {
                    b.HasBaseType("SistemaPedidos.Core.Models.Producto");

                    b.Property<string>("UrlDescarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Digital");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Nombre = "Software Visual Studio Professional",
                            Precio = 499.99m,
                            Stock = 999,
                            UrlDescarga = "https://download.microsoft.com/vspr"
                        });
                });

            modelBuilder.Entity("SistemaPedidos.Core.Models.ProductoFisico", b =>
                {
                    b.HasBaseType("SistemaPedidos.Core.Models.Producto");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Fisico");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Laptop Dell XPS",
                            Precio = 1200.00m,
                            Stock = 5,
                            PesoKg = 2.5m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mouse Logitech",
                            Precio = 30.00m,
                            Stock = 50,
                            PesoKg = 0.1m
                        });
                });

            modelBuilder.Entity("SistemaPedidos.Core.Models.ItemPedido", b =>
                {
                    b.HasOne("SistemaPedidos.Core.Models.Pedido", "Pedido")
                        .WithMany("ItemsNavigation")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPedidos.Core.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaPedidos.Core.Models.Pedido", b =>
                {
                    b.Navigation("ItemsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
